import { Book, Category, UserBadge } from './types';

export const CATEGORIES: Category[] = [
  { id: 'fiction', name: 'Fiction', count: 10, iconName: 'BookOpen', glowGradient: 'from-orange-500 to-amber-600' },
  { id: 'non-fiction', name: 'Non-Fiction', count: 3, iconName: 'Compass', glowGradient: 'from-emerald-500 to-teal-600' },
  { id: 'mythology', name: 'Mythology', count: 2, iconName: 'Sparkles', glowGradient: 'from-amber-600 to-red-700' },
  { id: 'self-help', name: 'Self-Help', count: 1, iconName: 'TrendingUp', glowGradient: 'from-blue-500 to-indigo-600' },
  { id: 'poetry', name: 'Poetry', count: 1, iconName: 'Heart', glowGradient: 'from-pink-500 to-rose-600' },
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'b1',
    title: 'Five Point Someone',
    author: 'Chetan Bhagat',
    isbn: '978-81-291-0459-5',
    category: 'Fiction',
    rating: 4.5,
    available: true,
    count: 4,
    description: 'A contemporary Indian fiction masterpiece detailing the life of three friends inside IIT who struggle with academic expectations, friendships, and dreams.',
    coverGradient: 'from-amber-500 via-orange-500 to-amber-700',
    coverImage: '/src/assets/images/fiction_book_cover_1779809349705.png',
    accentColor: '#eab308',
    year: 2004,
    pages: 270,
    reviews: [
      { id: 'r1', userName: 'Avi Shastry', rating: 5, comment: 'Highly relatable, captured the essence of college life perfectly!', date: '2026-05-18' }
    ]
  },
  {
    id: 'b2',
    title: 'The God of Small Things',
    author: 'Arundhati Roy',
    isbn: '978-0679457312',
    category: 'Fiction',
    rating: 4.8,
    available: true,
    count: 2,
    description: 'The Booker Prize-winning novel that explores how small, seemingly insignificant details shape the lives and destinies of fraternal twins in Kerala.',
    coverGradient: 'from-emerald-600 via-teal-700 to-indigo-800',
    coverImage: '/src/assets/images/fine_balance_cover_1779797935233.png',
    accentColor: '#10b981',
    year: 1997,
    pages: 340,
    reviews: [
      { id: 'r2', userName: 'Meera Nair', rating: 5, comment: 'Astonishing prose style, truly a masterpiece!', date: '2026-05-22' }
    ]
  },
  {
    id: 'b3',
    title: 'A Fine Balance',
    author: 'Rohinton Mistry',
    isbn: '978-0571190843',
    category: 'Fiction',
    rating: 4.9,
    available: true,
    count: 3,
    description: 'Set in mid-1970s India, this breathtaking epic captures the human spirit as four diverse characters form an unexpected bond under trying national circumstances.',
    coverGradient: 'from-rose-500 via-pink-600 to-purple-800',
    coverImage: '/src/assets/images/five_point_cover_1779797899585.png',
    accentColor: '#f43f5e',
    year: 1995,
    pages: 600,
    reviews: []
  },
  {
    id: 'b4',
    title: 'The White Tiger',
    author: 'Aravind Adiga',
    isbn: '978-1416562597',
    category: 'Fiction',
    rating: 4.7,
    available: true,
    count: 2,
    description: 'A brilliant satire on class struggles and socio-economic dynamics in modern India, as told through the micro-chronicles of a chauffeur-turned-entrepreneur.',
    coverGradient: 'from-stone-700 via-stone-800 to-emerald-950',
    coverImage: '/src/assets/images/god_small_cover_1779797918712.png',
    accentColor: '#14532d',
    year: 2008,
    pages: 320,
    reviews: []
  },
  {
    id: 'b5',
    title: 'A Suitable Boy',
    author: 'Vikram Seth',
    isbn: '978-0060786526',
    category: 'Fiction',
    rating: 4.9,
    available: true,
    count: 1,
    description: 'One of the longest novels in the English language, this masterpiece explores post-independence India through four families seeking the perfect spouse for Lata.',
    coverGradient: 'from-indigo-500 via-purple-600 to-slate-800',
    coverImage: '/src/assets/images/suitable_boy_cover_1779797969188.png',
    accentColor: '#6366f1',
    year: 1993,
    pages: 1349,
    reviews: []
  },
  {
    id: 'b6',
    title: 'The Inheritance of Loss',
    author: 'Kiran Desai',
    isbn: '978-0802142818',
    category: 'Fiction',
    rating: 4.6,
    available: true,
    count: 3,
    description: 'Set in the Himalayas, this Booker Prize-winning novel explores identity, globalization, and cultural patterns through the eyes of an embittered judge, his granddaughter, and his cook.',
    coverGradient: 'from-emerald-500 via-teal-600 to-lime-900',
    coverImage: '/src/assets/images/white_tiger_cover_1779797950754.png',
    accentColor: '#059669',
    year: 2006,
    pages: 380,
    reviews: []
  },
  {
    id: 'b7',
    title: "Midnight's Children",
    author: 'Salman Rushdie',
    isbn: '978-0099582076',
    category: 'Fiction',
    rating: 4.8,
    available: true,
    count: 2,
    description: 'A highly acclaimed masterpiece blending magical realism with historical events, focused on children born at the exact midnight hour of Indian Independence.',
    coverGradient: 'from-violet-500 via-fuchsia-700 to-rose-950',
    coverImage: '/src/assets/images/fiction_book_cover_2_1779809866675.png',
    accentColor: '#a21caf',
    year: 1981,
    pages: 550,
    reviews: []
  },
  {
    id: 'b8',
    title: 'Indian Mythology',
    author: 'Devdutt Pattanaik',
    isbn: '978-0892818709',
    category: 'Mythology',
    rating: 4.7,
    available: true,
    count: 3,
    description: 'A comprehensive, illustrative guide explaining symbols, narratives, and core philosophies behind the rich traditions of Indian mythological legends.',
    coverGradient: 'from-orange-500 via-amber-600 to-red-800',
    coverImage: '/src/assets/images/mythology_book_cover_1779809393535.png',
    accentColor: '#ea580c',
    year: 2003,
    pages: 240,
    reviews: []
  },
  {
    id: 'b9',
    title: 'The Pathless Path',
    author: 'Preeti Shenoy',
    isbn: '978-9353337196',
    category: 'Self-Help',
    rating: 4.4,
    available: true,
    count: 4,
    description: 'A refreshing self-help guide helping young Indian readers navigate career dilemmas, choose unconventional fields, and craft their own definition of success.',
    coverGradient: 'from-blue-500 via-indigo-600 to-teal-700',
    coverImage: '/src/assets/images/self_help_book_cover_1779809410942.png',
    accentColor: '#2563eb',
    year: 2020,
    pages: 220,
    reviews: []
  },
  {
    id: 'b10',
    title: 'Awake and Dreaming',
    author: 'Chetan Bhagat',
    isbn: '978-8129132543',
    category: 'Poetry',
    rating: 4.3,
    available: true,
    count: 3,
    description: 'An elegant collection of short poetical works, thoughts, and reflections capturing the spirit of youth, hope, and aspirations in changing seasons.',
    coverGradient: 'from-pink-500 via-rose-500 to-red-700',
    coverImage: '/src/assets/images/awake_dreaming_cover_1779810859756.png',
    accentColor: '#ec4899',
    year: 2008,
    pages: 160,
    reviews: []
  },
  {
    id: 'b11',
    title: 'The Palace of Illusions',
    author: 'Chitra Banerjee Divakaruni',
    isbn: '978-0385519732',
    category: 'Mythology',
    rating: 4.8,
    available: true,
    count: 2,
    description: 'A reimagining of the world-famous Mahabharata epic from the unique, poetic perspective of Panchali (Draupadi), exploring friendship, destiny, and power.',
    coverGradient: 'from-purple-600 via-indigo-700 to-orange-950',
    coverImage: '/src/assets/images/palace_illusions_cover_1779810875135.png',
    accentColor: '#7c3aed',
    year: 2008,
    pages: 360,
    reviews: []
  },
  {
    id: 'b12',
    title: 'Matru Devi Se Sanjay Tak',
    author: 'Sudha Murty',
    isbn: '978-0143451624',
    category: 'Fiction',
    rating: 4.9,
    available: true,
    count: 5,
    description: 'Heartwarming contemporary chronicles, values, and simple wisdom written with loving humanistic depth by India’s favorite storyteller Sudha Murty.',
    coverGradient: 'from-orange-400 via-red-500 to-amber-800',
    coverImage: '/src/assets/images/matru_devi_sanjay_tak_cover_1779810890860.png',
    accentColor: '#f97316',
    year: 2020,
    pages: 210,
    reviews: []
  },
  {
    id: 'b13',
    title: 'The Elephant, the Tiger, and the Cellphone',
    author: 'Shashi Tharoor',
    isbn: '978-0802142801',
    category: 'Non-Fiction',
    rating: 4.7,
    available: true,
    count: 2,
    description: 'A witty, highly analytical overview of how 21st-century India transformed into an emerging global digital powerhouse, balancing tradition and modernization.',
    coverGradient: 'from-sky-500 via-blue-600 to-indigo-800',
    coverImage: '/src/assets/images/the_elephant_tiger_cellphone_cover_1779810841349.png',
    accentColor: '#0ea5e9',
    year: 2007,
    pages: 410,
    reviews: []
  },
  {
    id: 'b14',
    title: 'Mother Mary Comes to Me',
    author: 'Arundhati Roy',
    isbn: '978-0593596716',
    category: 'Non-Fiction',
    rating: 4.8,
    available: true,
    count: 1,
    description: 'A brand new deeply personal memo-chronicle detailing the layers of memories, socio-political currents, and structural literary inspirations of the author.',
    coverGradient: 'from-teal-500 via-emerald-600 to-cyan-800',
    coverImage: '/src/assets/images/non_fiction_book_cover_2_1779809921849.png',
    accentColor: '#0d9488',
    year: 2025,
    pages: 290,
    reviews: []
  },
  {
    id: 'b15',
    title: 'The Far Field',
    author: 'Madhuri Vijay',
    isbn: '978-1984820038',
    category: 'Fiction',
    rating: 4.6,
    available: true,
    count: 2,
    description: 'An exceptional debut traveling across regional layers of modern India, capturing personal secrets, grief, and political tides with exquisite precision.',
    coverGradient: 'from-blue-800 via-indigo-900 to-slate-950',
    coverImage: '/src/assets/images/fiction_book_cover_5_1779809938285.png',
    accentColor: '#1e40af',
    year: 2019,
    pages: 430,
    reviews: []
  }
];

export const BADGES: UserBadge[] = [
  { id: 'first_book', name: 'India Scholar', description: 'Joined the premier Bharat eLibrary network', icon: 'BookOpen' },
  { id: 'no_fines', name: 'Ideal Citizen', description: 'Returned a book before the deadline with zero fines', icon: 'ShieldCheck' },
  { id: 'three_genres', name: 'Polymorphic Scholar', description: 'Issued books from 3 or more distinctive categories', icon: 'Layers' },
  { id: 'critic', name: 'Digital Scribe', description: 'Submitted a review or rating for any book in our catalog', icon: 'CheckCircle' }
];
